import { ElementCategory, PeriodicElement } from './types';

export const ELEMENTS: PeriodicElement[] = [
  { number: 1, symbol: 'H', name: '氢', atomicMass: '1.008', category: ElementCategory.Nonmetal, group: 1, period: 1 },
  { number: 2, symbol: 'He', name: '氦', atomicMass: '4.0026', category: ElementCategory.NobleGas, group: 18, period: 1 },
  { number: 3, symbol: 'Li', name: '锂', atomicMass: '6.94', category: ElementCategory.AlkaliMetal, group: 1, period: 2 },
  { number: 4, symbol: 'Be', name: '铍', atomicMass: '9.0122', category: ElementCategory.AlkalineEarthMetal, group: 2, period: 2 },
  { number: 5, symbol: 'B', name: '硼', atomicMass: '10.81', category: ElementCategory.Metalloid, group: 13, period: 2 },
  { number: 6, symbol: 'C', name: '碳', atomicMass: '12.011', category: ElementCategory.Nonmetal, group: 14, period: 2 },
  { number: 7, symbol: 'N', name: '氮', atomicMass: '14.007', category: ElementCategory.Nonmetal, group: 15, period: 2 },
  { number: 8, symbol: 'O', name: '氧', atomicMass: '15.999', category: ElementCategory.Nonmetal, group: 16, period: 2 },
  { number: 9, symbol: 'F', name: '氟', atomicMass: '18.998', category: ElementCategory.Halogen, group: 17, period: 2 },
  { number: 10, symbol: 'Ne', name: '氖', atomicMass: '20.180', category: ElementCategory.NobleGas, group: 18, period: 2 },
  { number: 11, symbol: 'Na', name: '钠', atomicMass: '22.990', category: ElementCategory.AlkaliMetal, group: 1, period: 3 },
  { number: 12, symbol: 'Mg', name: '镁', atomicMass: '24.305', category: ElementCategory.AlkalineEarthMetal, group: 2, period: 3 },
  { number: 13, symbol: 'Al', name: '铝', atomicMass: '26.982', category: ElementCategory.PostTransitionMetal, group: 13, period: 3 },
  { number: 14, symbol: 'Si', name: '硅', atomicMass: '28.085', category: ElementCategory.Metalloid, group: 14, period: 3 },
  { number: 15, symbol: 'P', name: '磷', atomicMass: '30.974', category: ElementCategory.Nonmetal, group: 15, period: 3 },
  { number: 16, symbol: 'S', name: '硫', atomicMass: '32.06', category: ElementCategory.Nonmetal, group: 16, period: 3 },
  { number: 17, symbol: 'Cl', name: '氯', atomicMass: '35.45', category: ElementCategory.Halogen, group: 17, period: 3 },
  { number: 18, symbol: 'Ar', name: '氩', atomicMass: '39.948', category: ElementCategory.NobleGas, group: 18, period: 3 },
  { number: 19, symbol: 'K', name: '钾', atomicMass: '39.098', category: ElementCategory.AlkaliMetal, group: 1, period: 4 },
  { number: 20, symbol: 'Ca', name: '钙', atomicMass: '40.078', category: ElementCategory.AlkalineEarthMetal, group: 2, period: 4 },
  { number: 21, symbol: 'Sc', name: '钪', atomicMass: '44.956', category: ElementCategory.TransitionMetal, group: 3, period: 4 },
  { number: 22, symbol: 'Ti', name: '钛', atomicMass: '47.867', category: ElementCategory.TransitionMetal, group: 4, period: 4 },
  { number: 23, symbol: 'V', name: '钒', atomicMass: '50.942', category: ElementCategory.TransitionMetal, group: 5, period: 4 },
  { number: 24, symbol: 'Cr', name: '铬', atomicMass: '51.996', category: ElementCategory.TransitionMetal, group: 6, period: 4 },
  { number: 25, symbol: 'Mn', name: '锰', atomicMass: '54.938', category: ElementCategory.TransitionMetal, group: 7, period: 4 },
  { number: 26, symbol: 'Fe', name: '铁', atomicMass: '55.845', category: ElementCategory.TransitionMetal, group: 8, period: 4 },
  { number: 27, symbol: 'Co', name: '钴', atomicMass: '58.933', category: ElementCategory.TransitionMetal, group: 9, period: 4 },
  { number: 28, symbol: 'Ni', name: '镍', atomicMass: '58.693', category: ElementCategory.TransitionMetal, group: 10, period: 4 },
  { number: 29, symbol: 'Cu', name: '铜', atomicMass: '63.546', category: ElementCategory.TransitionMetal, group: 11, period: 4 },
  { number: 30, symbol: 'Zn', name: '锌', atomicMass: '65.38', category: ElementCategory.TransitionMetal, group: 12, period: 4 },
  { number: 31, symbol: 'Ga', name: '镓', atomicMass: '69.723', category: ElementCategory.PostTransitionMetal, group: 13, period: 4 },
  { number: 32, symbol: 'Ge', name: '锗', atomicMass: '72.63', category: ElementCategory.Metalloid, group: 14, period: 4 },
  { number: 33, symbol: 'As', name: '砷', atomicMass: '74.922', category: ElementCategory.Metalloid, group: 15, period: 4 },
  { number: 34, symbol: 'Se', name: '硒', atomicMass: '78.96', category: ElementCategory.Nonmetal, group: 16, period: 4 },
  { number: 35, symbol: 'Br', name: '溴', atomicMass: '79.904', category: ElementCategory.Halogen, group: 17, period: 4 },
  { number: 36, symbol: 'Kr', name: '氪', atomicMass: '83.798', category: ElementCategory.NobleGas, group: 18, period: 4 },
  { number: 37, symbol: 'Rb', name: '铷', atomicMass: '85.468', category: ElementCategory.AlkaliMetal, group: 1, period: 5 },
  { number: 38, symbol: 'Sr', name: '锶', atomicMass: '87.62', category: ElementCategory.AlkalineEarthMetal, group: 2, period: 5 },
  { number: 39, symbol: 'Y', name: '钇', atomicMass: '88.906', category: ElementCategory.TransitionMetal, group: 3, period: 5 },
  { number: 40, symbol: 'Zr', name: '锆', atomicMass: '91.224', category: ElementCategory.TransitionMetal, group: 4, period: 5 },
  { number: 41, symbol: 'Nb', name: '铌', atomicMass: '92.906', category: ElementCategory.TransitionMetal, group: 5, period: 5 },
  { number: 42, symbol: 'Mo', name: '钼', atomicMass: '95.95', category: ElementCategory.TransitionMetal, group: 6, period: 5 },
  { number: 43, symbol: 'Tc', name: '锝', atomicMass: '98', category: ElementCategory.TransitionMetal, group: 7, period: 5 },
  { number: 44, symbol: 'Ru', name: '钌', atomicMass: '101.07', category: ElementCategory.TransitionMetal, group: 8, period: 5 },
  { number: 45, symbol: 'Rh', name: '铑', atomicMass: '102.91', category: ElementCategory.TransitionMetal, group: 9, period: 5 },
  { number: 46, symbol: 'Pd', name: '钯', atomicMass: '106.42', category: ElementCategory.TransitionMetal, group: 10, period: 5 },
  { number: 47, symbol: 'Ag', name: '银', atomicMass: '107.87', category: ElementCategory.TransitionMetal, group: 11, period: 5 },
  { number: 48, symbol: 'Cd', name: '镉', atomicMass: '112.41', category: ElementCategory.TransitionMetal, group: 12, period: 5 },
  { number: 49, symbol: 'In', name: '铟', atomicMass: '114.82', category: ElementCategory.PostTransitionMetal, group: 13, period: 5 },
  { number: 50, symbol: 'Sn', name: '锡', atomicMass: '118.71', category: ElementCategory.PostTransitionMetal, group: 14, period: 5 },
  { number: 51, symbol: 'Sb', name: '锑', atomicMass: '121.76', category: ElementCategory.Metalloid, group: 15, period: 5 },
  { number: 52, symbol: 'Te', name: '碲', atomicMass: '127.60', category: ElementCategory.Metalloid, group: 16, period: 5 },
  { number: 53, symbol: 'I', name: '碘', atomicMass: '126.90', category: ElementCategory.Halogen, group: 17, period: 5 },
  { number: 54, symbol: 'Xe', name: '氙', atomicMass: '131.29', category: ElementCategory.NobleGas, group: 18, period: 5 },
  { number: 55, symbol: 'Cs', name: '铯', atomicMass: '132.91', category: ElementCategory.AlkaliMetal, group: 1, period: 6 },
  { number: 56, symbol: 'Ba', name: '钡', atomicMass: '137.33', category: ElementCategory.AlkalineEarthMetal, group: 2, period: 6 },
  { number: 57, symbol: 'La', name: '镧', atomicMass: '138.91', category: ElementCategory.Lanthanide, group: 4, period: 9 }, 
  { number: 58, symbol: 'Ce', name: '铈', atomicMass: '140.12', category: ElementCategory.Lanthanide, group: 5, period: 9 },
  { number: 59, symbol: 'Pr', name: '镨', atomicMass: '140.91', category: ElementCategory.Lanthanide, group: 6, period: 9 },
  { number: 60, symbol: 'Nd', name: '钕', atomicMass: '144.24', category: ElementCategory.Lanthanide, group: 7, period: 9 },
  { number: 61, symbol: 'Pm', name: '钷', atomicMass: '145', category: ElementCategory.Lanthanide, group: 8, period: 9 },
  { number: 62, symbol: 'Sm', name: '钐', atomicMass: '150.36', category: ElementCategory.Lanthanide, group: 9, period: 9 },
  { number: 63, symbol: 'Eu', name: '铕', atomicMass: '151.96', category: ElementCategory.Lanthanide, group: 10, period: 9 },
  { number: 64, symbol: 'Gd', name: '钆', atomicMass: '157.25', category: ElementCategory.Lanthanide, group: 11, period: 9 },
  { number: 65, symbol: 'Tb', name: '铽', atomicMass: '158.93', category: ElementCategory.Lanthanide, group: 12, period: 9 },
  { number: 66, symbol: 'Dy', name: '镝', atomicMass: '162.50', category: ElementCategory.Lanthanide, group: 13, period: 9 },
  { number: 67, symbol: 'Ho', name: '钬', atomicMass: '164.93', category: ElementCategory.Lanthanide, group: 14, period: 9 },
  { number: 68, symbol: 'Er', name: '铒', atomicMass: '167.26', category: ElementCategory.Lanthanide, group: 15, period: 9 },
  { number: 69, symbol: 'Tm', name: '铥', atomicMass: '168.93', category: ElementCategory.Lanthanide, group: 16, period: 9 },
  { number: 70, symbol: 'Yb', name: '镱', atomicMass: '173.04', category: ElementCategory.Lanthanide, group: 17, period: 9 },
  { number: 71, symbol: 'Lu', name: '镥', atomicMass: '174.97', category: ElementCategory.Lanthanide, group: 18, period: 9 },
  { number: 72, symbol: 'Hf', name: '铪', atomicMass: '178.49', category: ElementCategory.TransitionMetal, group: 4, period: 6 },
  { number: 73, symbol: 'Ta', name: '钽', atomicMass: '180.95', category: ElementCategory.TransitionMetal, group: 5, period: 6 },
  { number: 74, symbol: 'W', name: '钨', atomicMass: '183.84', category: ElementCategory.TransitionMetal, group: 6, period: 6 },
  { number: 75, symbol: 'Re', name: '铼', atomicMass: '186.21', category: ElementCategory.TransitionMetal, group: 7, period: 6 },
  { number: 76, symbol: 'Os', name: '锇', atomicMass: '190.23', category: ElementCategory.TransitionMetal, group: 8, period: 6 },
  { number: 77, symbol: 'Ir', name: '铱', atomicMass: '192.22', category: ElementCategory.TransitionMetal, group: 9, period: 6 },
  { number: 78, symbol: 'Pt', name: '铂', atomicMass: '195.08', category: ElementCategory.TransitionMetal, group: 10, period: 6 },
  { number: 79, symbol: 'Au', name: '金', atomicMass: '196.97', category: ElementCategory.TransitionMetal, group: 11, period: 6 },
  { number: 80, symbol: 'Hg', name: '汞', atomicMass: '200.59', category: ElementCategory.TransitionMetal, group: 12, period: 6 },
  { number: 81, symbol: 'Tl', name: '铊', atomicMass: '204.38', category: ElementCategory.PostTransitionMetal, group: 13, period: 6 },
  { number: 82, symbol: 'Pb', name: '铅', atomicMass: '207.2', category: ElementCategory.PostTransitionMetal, group: 14, period: 6 },
  { number: 83, symbol: 'Bi', name: '铋', atomicMass: '208.98', category: ElementCategory.PostTransitionMetal, group: 15, period: 6 },
  { number: 84, symbol: 'Po', name: '钋', atomicMass: '209', category: ElementCategory.Metalloid, group: 16, period: 6 },
  { number: 85, symbol: 'At', name: '砹', atomicMass: '210', category: ElementCategory.Halogen, group: 17, period: 6 },
  { number: 86, symbol: 'Rn', name: '氡', atomicMass: '222', category: ElementCategory.NobleGas, group: 18, period: 6 },
  { number: 87, symbol: 'Fr', name: '钫', atomicMass: '223', category: ElementCategory.AlkaliMetal, group: 1, period: 7 },
  { number: 88, symbol: 'Ra', name: '镭', atomicMass: '226', category: ElementCategory.AlkalineEarthMetal, group: 2, period: 7 },
  { number: 89, symbol: 'Ac', name: '锕', atomicMass: '227', category: ElementCategory.Actinide, group: 4, period: 10 },
  { number: 90, symbol: 'Th', name: '钍', atomicMass: '232.04', category: ElementCategory.Actinide, group: 5, period: 10 },
  { number: 91, symbol: 'Pa', name: '镤', atomicMass: '231.04', category: ElementCategory.Actinide, group: 6, period: 10 },
  { number: 92, symbol: 'U', name: '铀', atomicMass: '238.03', category: ElementCategory.Actinide, group: 7, period: 10 },
  { number: 93, symbol: 'Np', name: '镎', atomicMass: '237', category: ElementCategory.Actinide, group: 8, period: 10 },
  { number: 94, symbol: 'Pu', name: '钚', atomicMass: '244', category: ElementCategory.Actinide, group: 9, period: 10 },
  { number: 95, symbol: 'Am', name: '镅', atomicMass: '243', category: ElementCategory.Actinide, group: 10, period: 10 },
  { number: 96, symbol: 'Cm', name: '锔', atomicMass: '247', category: ElementCategory.Actinide, group: 11, period: 10 },
  { number: 97, symbol: 'Bk', name: '锫', atomicMass: '247', category: ElementCategory.Actinide, group: 12, period: 10 },
  { number: 98, symbol: 'Cf', name: '锎', atomicMass: '251', category: ElementCategory.Actinide, group: 13, period: 10 },
  { number: 99, symbol: 'Es', name: '锿', atomicMass: '252', category: ElementCategory.Actinide, group: 14, period: 10 },
  { number: 100, symbol: 'Fm', name: '镄', atomicMass: '257', category: ElementCategory.Actinide, group: 15, period: 10 },
  { number: 101, symbol: 'Md', name: '钔', atomicMass: '258', category: ElementCategory.Actinide, group: 16, period: 10 },
  { number: 102, symbol: 'No', name: '锘', atomicMass: '259', category: ElementCategory.Actinide, group: 17, period: 10 },
  { number: 103, symbol: 'Lr', name: '铹', atomicMass: '262', category: ElementCategory.Actinide, group: 18, period: 10 },
  { number: 104, symbol: 'Rf', name: '𬬻', atomicMass: '267', category: ElementCategory.TransitionMetal, group: 4, period: 7 },
  { number: 105, symbol: 'Db', name: '𬭊', atomicMass: '268', category: ElementCategory.TransitionMetal, group: 5, period: 7 },
  { number: 106, symbol: 'Sg', name: '𬭳', atomicMass: '271', category: ElementCategory.TransitionMetal, group: 6, period: 7 },
  { number: 107, symbol: 'Bh', name: '𬭛', atomicMass: '272', category: ElementCategory.TransitionMetal, group: 7, period: 7 },
  { number: 108, symbol: 'Hs', name: '𬭶', atomicMass: '270', category: ElementCategory.TransitionMetal, group: 8, period: 7 },
  { number: 109, symbol: 'Mt', name: '***', atomicMass: '276', category: ElementCategory.Unknown, group: 9, period: 7 },
  { number: 110, symbol: 'Ds', name: '***', atomicMass: '281', category: ElementCategory.Unknown, group: 10, period: 7 },
  { number: 111, symbol: 'Rg', name: '𬬭', atomicMass: '280', category: ElementCategory.Unknown, group: 11, period: 7 },
  { number: 112, symbol: 'Cn', name: '***', atomicMass: '285', category: ElementCategory.Unknown, group: 12, period: 7 },
  { number: 113, symbol: 'Nh', name: '***', atomicMass: '284', category: ElementCategory.Unknown, group: 13, period: 7 },
  { number: 114, symbol: 'Fl', name: '***', atomicMass: '289', category: ElementCategory.Unknown, group: 14, period: 7 },
  { number: 115, symbol: 'Mc', name: '***', atomicMass: '288', category: ElementCategory.Unknown, group: 15, period: 7 },
  { number: 116, symbol: 'Lv', name: '***', atomicMass: '293', category: ElementCategory.Unknown, group: 16, period: 7 },
  { number: 117, symbol: 'Ts', name: '***', atomicMass: '294', category: ElementCategory.Unknown, group: 17, period: 7 },
  { number: 118, symbol: 'Og', name: '***', atomicMass: '294', category: ElementCategory.Unknown, group: 18, period: 7 },
];

export const CATEGORY_COLORS: Record<ElementCategory, string> = {
  [ElementCategory.Nonmetal]: 'border-green-400 text-green-400 bg-green-400/10',
  [ElementCategory.NobleGas]: 'border-purple-400 text-purple-400 bg-purple-400/10',
  [ElementCategory.AlkaliMetal]: 'border-red-400 text-red-400 bg-red-400/10',
  [ElementCategory.AlkalineEarthMetal]: 'border-orange-400 text-orange-400 bg-orange-400/10',
  [ElementCategory.Metalloid]: 'border-teal-400 text-teal-400 bg-teal-400/10',
  [ElementCategory.Halogen]: 'border-yellow-300 text-yellow-300 bg-yellow-300/10',
  [ElementCategory.TransitionMetal]: 'border-blue-400 text-blue-400 bg-blue-400/10',
  [ElementCategory.PostTransitionMetal]: 'border-indigo-400 text-indigo-400 bg-indigo-400/10',
  [ElementCategory.Lanthanide]: 'border-pink-400 text-pink-400 bg-pink-400/10',
  [ElementCategory.Actinide]: 'border-rose-500 text-rose-500 bg-rose-500/10',
  [ElementCategory.Unknown]: 'border-gray-500 text-gray-500 bg-gray-500/10',
};
